Overlay and its composing components take a portalContainerName prop
primer/react pull request #1388
Opened 2021-08-23 21:31 UTC by jfuchs

This change adds a `portalContainerName` prop to `Overlay`, `AnchoredOverlay`, `DropdownMenu`, `SelectPanel`, and `ActionMenu`.

Closes #1169.

### Screenshots

https://user-images.githubusercontent.com/21195/130521483-10a9c965-5dfb-43c0-9692-ee6ae12de624.mov

### Merge checklist

- [ ] Added/updated tests
- [X] Added/updated documentation
- [X] Tested in Chrome
- [ ] Tested in Firefox
- [ ] Tested in Safari
- [ ] Tested in Edge

Take a look at the [What we look for in reviews](https://github.com/primer/react/blob/main/contributor-docs/CONTRIBUTING.md#what-we-look-for-in-reviews) section of the contributing guidelines for more information on how we review PRs.

2021-08-24 00:01 UTC, colebemis commented
Could you explain why the `portalContainerName` prop is necessary?

2021-08-31 17:13 UTC, colebemis commented
@jfuchs That makes sense! Can you add that to the PR description and the changeset?

2021-08-31 18:24 UTC, dgreif requested changes
Looks like the right approach, but I think we can simplify this quite a bit by leveraging the existing props

2021-08-31 18:24 UTC, dgreif commented on docs/content/ActionMenu.mdx
> +| portalContainerName | boolean                               |    `undefined`    | Optional. See the `portalContainerName` prop of `Overlay`
Looks like this type is wrong (in each of the docs). Should be `string`

2021-08-31 18:24 UTC, dgreif commented on src/stories/AnchoredOverlay.stories.tsx
> +    }
This story doesn't appear to use `portalContainerName`.  Instead, it looks like it just registers the default portal within the scrolling element

2021-08-31 18:24 UTC, dgreif commented on src/AnchoredOverlay/AnchoredOverlay.tsx
>            {...overlayProps}
We already have an option to pass any `overlayProps` through the Anchored Overlays, which seems like an OK path for this option as well.  It should be rarely used, kind of like height/width which use this other approach.  Should significantly cut down on the surface area of this PR as well

2021-09-01 03:30 UTC, dgreif approved these changes
Looks much cleaner, thanks for simplifying and updating the stories!  One small item then this should be good to go

2021-09-01 03:30 UTC, dgreif commented on src/Overlay.tsx
> +  portalContainerName?: string
We should only need to define this prop in `OverlayProps`.  The values here are specifically for what gets passed in to the styled component.  You should be able to remove this line without issues

2021-09-01 19:44 UTC, dgreif approved these changes

2021-09-01 19:44 UTC, merged