Deprecate ChoiceFieldset and ChoiceInputField
primer/react pull request #1900
Opened 2022-02-25 19:24 UTC by mperrotti

2022-02-25 19:25 UTC, mperrotti commented
Duplicate of https://github.com/primer/react/pull/1891

2022-02-28 09:55 UTC, rezrah commented on .changeset/nervous-pets-sleep.md
> +  <CheckboxGroup.Label>Prefered Primer component interface</CheckboxGroup.Label>
small typo

```suggestion
  <CheckboxGroup.Label>Preferred Primer component interface</CheckboxGroup.Label>
```

2022-02-28 09:57 UTC, rezrah commented on .changeset/nervous-pets-sleep.md
> +![image](https://user-images.githubusercontent.com/2313998/155632630-60822d7b-6053-480d-925d-cea4d3b04919.png)
If we go with these banners in the change logs*, can we change this to a more descriptive caption here please? 

Also, wondering what you think about switching the labels and group headings to be more product-oriented in the banner, like they are in code snippets? 

* Not sure if we are doing banners, as other PRs don't include them. We'd need to backfill them.

2022-02-28 09:59 UTC, rezrah commented on .changeset/nervous-pets-sleep.md
> +  <ChoiceFieldset.Legend>Prefered Primer component interface</ChoiceFieldset.Legend>
FYI typo on preferred

2022-02-28 10:00 UTC, rezrah commented on .changeset/nervous-pets-sleep.md
> +<th> Before </th> <th> After </th>
```suggestion
<th> Before (v34) </th> <th> After (v35)</th>
```

2022-02-28 10:01 UTC, rezrah commented on .changeset/nervous-pets-sleep.md
> +  <ChoiceFieldset.Legend>Prefered Primer component interface</ChoiceFieldset.Legend>
The before / after is overflowing quite a lot.. is it possible to add more line breaks to the `before` snippet so it brings after more into view?

```suggestion
  <ChoiceFieldset.Legend>
    Prefered Primer component interface
  </ChoiceFieldset.Legend>
```

2022-02-28 11:57 UTC, siddharthkp commented
Using this checklist for review:

### User facing

- [x] Add changelog

API:
  - [x] Move from src/index to src/deprecated
  - [x] Add @deprecated JSDoc annotation

Docs:
  - [x] Update status to deprecated in docs
  - [ ] Add 'deprecated' to doc code examples (for ChoiceInputField)
  - [x] Add deprecation notice in docs
  - [ ] Move to deprecated section in docs/nav.yml
  - [ ] Move to deprecated folder in docs/
  

### Internal maintenance

- NA Update import path in related components

Tests
- [ ] Move to tests/deprecated/
- [ ] Update import path in tests
- [ ] Update test snapshots

Storybook:
- NA Update title in story meta "Deprecated components"
- NA Move to stories/deprecated/
- NA Update import path in stories

### Checks
- [ ] Docs working x (ChoiceInputField docs broken)
- [ ] Tests passing x
- [x] Storybook working

2022-02-28 11:59 UTC, siddharthkp requested changes
Using this checklist for review:

### Checks
- [ ] Docs working x (ChoiceInputField docs broken)
- [ ] Tests passing x
- [x] Storybook working

### User facing (should prioritise for release)

- [x] Add changelog

API:
  - [x] Move from src/index to src/deprecated
  - [x] Add `@deprecated` JSDoc annotation

Docs:
  - [x] Update status to deprecated in docs
  - [x] Add 'deprecated' to doc code examples (for ChoiceInputField)
  - [x] Add deprecation notice in docs
  - [ ] Move to deprecated section in docs/nav.yml
  - [ ] Move to deprecated folder in docs/
  

### Internal maintenance (not blocking, can tackle in a new PR)

- NA Update import path in related components

Tests
- [x] Move to tests/deprecated/
- [x] Update import path in tests
- [x] Update test snapshots

Storybook:
- NA Update title in story meta "Deprecated components"
- NA Move to stories/deprecated/
- NA Update import path in stories

2022-02-28 11:59 UTC, siddharthkp commented on src/index.ts
> -} from './PageLayout'
This seems unintentional?

2022-03-01 14:14 UTC, rezrah commented on .changeset/nervous-pets-sleep.md
> +The `CheckboxGroup` and `RadioGroup` components will be used to deprecate the `ChoiceFieldset` component. The deprecation of `ChoiceFieldset` also allows us to deprecate `ChoiceInputField`.
If it's a quick one, can we add the heading in? Happy to do it in the final changelog too, so no biggie

```
### ChoiceFieldset and ChoiceFieldset
```

2022-03-01 14:16 UTC, rezrah commented on src/deprecated/ChoiceInputField.tsx
> + * @deprecated Use `FormControl` instead. See https://primer.style/react/FormControl for more info
Have you verified this annotation works? I think it'll need to be applied at the bottom of the file in the object assignment instead.

2022-03-01 14:17 UTC, rezrah approved these changes
looks great.. just one observation here: https://github.com/primer/react/pull/1900/files#r816806465

2022-03-01 14:20 UTC, rezrah commented on src/deprecated/ChoiceFieldset/ChoiceFieldset.tsx
> + * @deprecated Use `CheckboxGroup` or `RadioGroup` instead. See https://primer.style/react/CheckboxGroup and https://primer.style/react/RadioGroup for more info
Similar feedback to the other annotation, I think this needs to be applied here:

```js
/**
  * @deprecated Use `CheckboxGroup` or `RadioGroup` instead. See https://primer.style/react/CheckboxGroup and https://primer.style/react/RadioGroup for more info
  */
export default Object.assign(ChoiceFieldset, {

```

2022-03-01 14:24 UTC, rezrah approved these changes

2022-03-01 15:28 UTC, merged