Fix pagelayout stories axe violations
primer/react pull request #3012
Opened 2023-03-10 17:07 UTC by radglob

Added `tabIndex` to the CustomStickyHeader story to fix an axe violation regarding scrollable regions not being focusable. We needed to add `tabIndex` to both the pane and the main content as without its own `tabIndex`, a user could not focus on the main content again.

Closes https://github.com/github/primer/issues/1865.

### Screenshots

Please provide before/after screenshots for any visual changes

### Merge checklist

- [ ] Added/updated tests
- [ ] Added/updated documentation
- [ ] Tested in Chrome
- [ ] Tested in Firefox
- [ ] Tested in Safari
- [ ] Tested in Edge

Take a look at the [What we look for in reviews](https://github.com/primer/react/blob/main/contributor-docs/CONTRIBUTING.md#what-we-look-for-in-reviews) section of the contributing guidelines for more information on how we review PRs.

2023-03-10 17:38 UTC, joshblack commented
Thanks for putting this up @radglob! Just wanted to double-check on requirements for this, I believe that for this we would need the following:

- The `PageLayout.Pane` component needs to be aware of overflow
- When overflow is detected, the `PageLayout.Pane` component will:
  - Add the `tabIndex` attribute[^1]
  - Add `role="region"`[^1]
  - Add `aria-label` with an accessible label or `aria-labelledby` to an appropriate element[^1]

A big challenge for this component seems to be getting that `aria-label` or `aria-labelledby` to be a valid that's relevant since it only accepts `children`.

Is that you're understanding as well for this issue @ericwbailey @TylerJDev? Or is there anything missing?

Let me know if that makes sense @radglob or if I'm overthinking this 🤔 

[^1]: https://www.tpgi.com/short-note-on-improving-usability-of-scrollable-regions/)

2023-03-13 17:52 UTC, TylerJDev commented
@joshblack - Yup, that is my understanding as well. I'm guessing we'll need to make the accessible name a required prop for `pane`? If so, we might need to emphasize on why that's needed so that developers give it a good name.

@radglob - Let me know if you want to pair on this issue! Josh listed all the items we'd need to make sure this is accessible, but if you have any questions on the accessible bits let me know! :grin:

2023-03-16 21:27 UTC, joshblack requested changes
Looks great! I think only big thing is to make sure that one story gets the `aria-label` to stop it from error'ing out. I left a couple other comments too, let me know what you think!

From a package release perspective, how do you feel about emitting a `warning` instead of an `error` for the missing `aria-label` or `aria-labelledby`? This could prompt people to add the label without potentially causing existing code to fail. Just wanted to get your thoughts on this 👀

2023-03-17 15:25 UTC, joshblack approved these changes
Looks great!

2023-03-17 16:13 UTC, merged