Deleted the files issue #2992
primer/react pull request #3059
Opened 2023-03-21 20:46 UTC by utkars3

Close #2992 

I had deleted the files that are to be deleted

2023-03-21 20:47 UTC, joshblack commented on src/Dialog.tsx
@broccolinisoup should these still be included in `src` or are they safe to be removed? 👀

2023-03-21 20:48 UTC, joshblack commented on src/ActionMenu.tsx
@langermank is this the right file to be removed for `ActionMenu` after the storybook refactor?

2023-03-21 20:50 UTC, utkars3 commented on src/Dialog.tsx
@joshblack  the issue was to delete the files.Have i done something wrong?

2023-03-21 20:57 UTC, joshblack commented on src/Dialog.tsx
Hey @utkars3! 👋 I think you're totally fine, just wanted to confirm the changes with @broccolinisoup since we ran into some issues specifically with Dialog in our last recent 👀 

Just wanted to say thanks for making this PR, by the way! We appreciate it a ton 🙏

2023-03-21 21:14 UTC, langermank commented on src/ActionMenu.tsx
Yes this is correct!

2023-03-21 21:21 UTC, broccolinisoup commented on src/Dialog.tsx
Thanks for pinging me @joshblack! Yes, as you mentioned we ran into some import/export issues last week and I [reverted](https://github.com/primer/react/pull/3040) the `Dialog` and `Dialog2` changes. That means, we will still need to keep `src/Dialog.tsx` and `src/Dialog.docs.json` for now.

2023-03-22 03:45 UTC, utkars3 commented on src/Dialog.tsx
@broccolinisoup whats about ActionMenu.tsx

2023-03-22 03:58 UTC, broccolinisoup commented on src/Dialog.tsx
`ActionMenu.tsx` is good to go! https://github.com/primer/react/pull/3059#discussion_r1143972912

2023-03-23 01:33 UTC, broccolinisoup requested changes
If we could take the `Dialog` and `Dialog2` changes back, this should be good 🙂

2023-05-22 22:51 UTC, broccolinisoup commented
Hi @utkars3 👋🏻 Are you still interested in following up with the changes? I think we need to only remove `ActionMenu.tsx`. Please see [this comment](https://github.com/primer/react/pull/3059#pullrequestreview-1353706358) as well

2023-05-23 11:45 UTC, utkars3 commented
@broccolinisoup ya i am interested to delete the files

2023-05-24 00:26 UTC, broccolinisoup commented
@utkars3 Great! Do you need help with resolving conflicts to start with?

2023-05-24 20:24 UTC, utkars3 commented
@broccolinisoup i have to delete ActionMenu.tsx?

2023-06-27 03:25 UTC, broccolinisoup commented
Hi @utkars3 sorry for missing your comment!

We need to resolve conflicts first. Apparently, there are new changes on the `src/ActionMenu.tsx` but in this PR we are trying to delete it, so git sees this as a conflict and this conflict needs to be resolved manually on the command line. There are instructions of how to do that if you click/enter "Use the command line" in the "This branch has conflicts that must be resolved" section. We also need to take the `Dialog` and `Dialog2` changes back as it is mentioned [here](https://github.com/primer/react/pull/3059#pullrequestreview-1353706358)

If resolving conflicts is an area that you are not familiar with, other option could be;
- Closing this PR
- Fetching `main`
- Create a new branch on top of the latest `main`
- Delete _only_ `src/ActionMenu.tsx`
- Push another PR

Thank you for your contribution 🙏🏻 Let me know if you need any help!

2023-09-02 04:04 UTC, closed without merging