Docs(Tooltip): Adds `defaultValue` of tooltip direction to documentation
primer/react pull request #3175
Opened 2023-04-17 02:44 UTC by edersonlucas

Describe your changes here.

The purpose of this PR is just to add the default tooltip direction value to the documentation. Which was reversed from PR #3169 . I apologize for not reviewing the review PR before the merge. Sorry.

### Screenshots

Please provide before/after screenshots for any visual changes

### Merge checklist

- [ ] Added/updated tests
- [x] Added/updated documentation
- [ ] Tested in Chrome
- [ ] Tested in Firefox
- [ ] Tested in Safari
- [ ] Tested in Edge

Take a look at the [What we look for in reviews](https://github.com/primer/react/blob/main/contributor-docs/CONTRIBUTING.md#what-we-look-for-in-reviews) section of the contributing guidelines for more information on how we review PRs.

2023-04-17 03:21 UTC, broccolinisoup requested changes
Hey @edersonlucas 👋🏻  Thanks for this PR! The doc looks good - We usually release docs only PRs without a changeset. I would suggest removing the changeset file and adding `skip changeset` label to the PR.

2023-04-17 03:35 UTC, edersonlucas commented
> Hey @edersonlucas 👋🏻 Thanks for this PR! The doc looks good - We usually release docs only PRs without a changeset. I would suggest removing the changeset file and adding `skip changeset` label to the PR.

Hi @broccolinisoup 👋 I removed the changeset. But I don't know how I add the label.

2023-04-17 03:38 UTC, broccolinisoup commented
No worries! I added the label. It is on the right sidebar with the title of `Labels`. Clicking the gear icon will pop up a list and you can add/remove labels to the pull request there.

2023-04-17 03:38 UTC, broccolinisoup approved these changes

2023-04-17 03:46 UTC, edersonlucas commented
> No worries! I added the label. It is on the right sidebar with the title of `Labels`. Clicking the gear icon will pop up a list and you can add/remove labels to the pull request there.

Oh yes✨. I found it on the side. Thanks🙏. But I don't have an add option. I believe I don't have that permission 🤔

2023-04-18 00:25 UTC, broccolinisoup commented
> > No worries! I added the label. It is on the right sidebar with the title of `Labels`. Clicking the gear icon will pop up a list and you can add/remove labels to the pull request there.
> 
> Oh yes✨. I found it on the side. Thanks🙏. But I don't have an add option. I believe I don't have that permission 🤔

Ah right! Thanks for letting me know!

2023-04-18 00:37 UTC, merged