Deprecate position prop for PageLayout.Pane, update stories and tests.
primer/react pull request #3389
Opened 2023-06-07 20:08 UTC by radglob

Deprecates the `position` prop for `PageLayout.Pane`. Partially addresses https://github.com/github/primer/issues/1199 in conjunction with https://github.com/primer/react/pull/3386.

### Screenshots

Please provide before/after screenshots for any visual changes

### Merge checklist

- [X] Added/updated tests
- [X] Added/updated documentation
- [X] Changes are [SSR compatible](https://github.com/primer/react/blob/main/contributor-docs/CONTRIBUTING.md#ssr-compatibility)
- [X] Tested in Chrome
- [X] Tested in Firefox
- [X] Tested in Safari
- [X] Tested in Edge

Take a look at the [What we look for in reviews](https://github.com/primer/react/blob/main/contributor-docs/CONTRIBUTING.md#what-we-look-for-in-reviews) section of the contributing guidelines for more information on how we review PRs.

2023-06-19 15:30 UTC, mperrotti commented
These changes look right to me. @colebemis - could you look at this one too?

2023-07-17 16:27 UTC, colebemis requested changes
Great work on this @radglob!

The only blocking feedback I have is that the gap between the content and pane regions disappears on narrow viewports. We should fix that before shipping this change.

I also made a couple comments about updating the stories and documentation of SplitPageLayout to match PageLayout.

2023-07-17 16:27 UTC, colebemis commented on src/PageLayout/PageLayout.tsx
> +
Love this incremental approach to breaking changes ❤️

2023-07-17 16:27 UTC, colebemis commented on src/PageLayout/PageLayout.stories.tsx
> -    // Pane prop controls
We should also remove these controls from the SplitPageLayout stories.

2023-07-17 16:27 UTC, colebemis commented on src/PageLayout/PageLayout.tsx
> +            })}
Looks like the gap between content and pane collapses on narrow screens. We probably need a `rowGap` in here somewhere.

![No gap between content and pane regions](https://github.com/primer/react/assets/4608155/45ff53d5-0ad0-40f9-9e76-ec7ee34d2973)

2023-07-17 16:27 UTC, colebemis commented on src/PageLayout/PageLayout.docs.json
> +          "deprecated": true
We should also deprecate `position` in  `SplitPageLayout.docs.json`

2023-07-18 15:29 UTC, merged