Added InlineAutocomplete stories
primer/react pull request #3639
Opened 2023-08-15 18:09 UTC by green6erry

Parent issue: https://github.com/github/primer/issues/1488

Add storybook stories for InlineAutocomplete (draft)

Checklist

- [ ]  Ensure your chosen component has a component directory in the src directory
- [ ]  Ensure the component has a root story file in the component directory
- [ ]  Ensure that the root story file exports a Default story
- [ ]  (Optional) Create a Playground story
- [ ]  Move all other stories for the component into a .features.stories.tsx file
- [ ]  Opt the component into storybook tests
- [ ]  (Optional) Create visual regression tests for the component

2023-09-18 00:08 UTC, broccolinisoup commented
Hello @green6erry would that be possible to resolve the merge conflicts before the review? Thank you 🙏🏻

2023-09-18 01:34 UTC, green6erry commented
> Hello @green6erry would that be possible to resolve the merge conflicts before the review? Thank you 🙏🏻

Done!

2023-09-19 00:32 UTC, broccolinisoup requested changes
Hello 👋🏻 VRT tests are failing, because they are still running on the "old" story ids. 

Because we renamed component stories in this PR from being `Components/Forms/InlineAutocomplete/...` to `Components/InlineAutocomplete/..` , their ids are changed too and we need to update them on https://github.com/primer/react/blob/main/e2e/components/InlineAutocomplete.test.ts so that the Playwright can run on these stories. Let me know if you have any questions! 

We will need to update the Playwright

2023-10-30 23:53 UTC, broccolinisoup commented on src/InlineAutocomplete/InlineAutocomplete.features.stories.tsx
> +  title: 'Components/InlineAutocomplete/Features',
Sorry, I didn't realised this component is draft. For draft components, we should serve them under the Drafts folder in storybook. 
```suggestion
  title: 'Drafts/Components/InlineAutocomplete/Features',
```

2023-10-30 23:53 UTC, broccolinisoup commented on src/InlineAutocomplete/InlineAutocomplete.stories.tsx
> +  title: 'Components/InlineAutocomplete',
```suggestion
  title: 'Drafts/Components/InlineAutocomplete',
```

2023-10-30 23:54 UTC, broccolinisoup commented on e2e/components/InlineAutocomplete.test.ts
> +            id: 'components-inlineautocomplete--default',
Based on the draft status ([reference](https://github.com/primer/react/pull/3639#discussion_r1376911543)), we should be re-updating them again. Sorry I missed the component status in the first review.

2023-10-30 23:55 UTC, broccolinisoup commented on e2e/components/InlineAutocomplete.test.ts
> +            id: 'components-inlineautocomplete--default',
i.e.
```suggestion
            id: 'drafts-components-inlineautocomplete--default',
```

2023-10-30 23:56 UTC, broccolinisoup commented on docs/content/drafts/InlineAutocomplete.mdx
>  storybook: '/react/storybook?path=/story/components-forms-inlineautocomplete--default'
```suggestion
storybook: '/react/storybook?path=/story/drafts-components-inlineautocomplete--default'
```

2023-10-31 14:37 UTC, green6erry commented
@broccolinisoup, There are issues with naming it back to `Drafts/...` because of Tooptip v2. I'm not sure how you'd like to delineate between them, but I was just trying to get a story for the v1 Tooltip so there was something. I think it will be up to you or someone that's not me to decide.

2023-10-31 15:01 UTC, joshblack requested changes
Looking great! ✨ Just left some comments on what I think the story ids ended up being with the move, hope they work 🤞

2023-10-31 15:01 UTC, joshblack commented on e2e/components/InlineAutocomplete.test.ts
> +            id: 'components-inlineautocomplete-features--custom-rendering',
```suggestion
            id: 'drafts-components-inlineautocomplete-features--custom-rendering',
```

2023-10-31 15:01 UTC, joshblack commented on e2e/components/InlineAutocomplete.test.ts
> +            id: 'components-inlineautocomplete-features--custom-rendering',
```suggestion
            id: 'drafts-components-inlineautocomplete-features--custom-rendering',
```

2023-10-31 15:01 UTC, joshblack commented on e2e/components/InlineAutocomplete.test.ts
> +            id: 'components-inlineautocomplete-features--single-line',
```suggestion
            id: 'drafts-components-inlineautocomplete-features--single-line',
```

2023-10-31 15:01 UTC, joshblack commented on e2e/components/InlineAutocomplete.test.ts
> +            id: 'components-inlineautocomplete-features--single-line',
```suggestion
            id: 'drafts-components-inlineautocomplete-features--single-line',
```

2023-10-31 17:23 UTC, green6erry reviewed
@broccolinisoup this also should be complete.

2023-10-31 21:36 UTC, broccolinisoup approved these changes

2023-10-31 23:14 UTC, merged