Added Tooltip stories
primer/react pull request #3881
Opened 2023-10-30 16:24 UTC by green6erry

Parent issue: https://github.com/github/primer/issues/1488

Add storybook stories for Tooltip

Checklist

- [x]  Ensure your chosen component has a component directory in the src directory
- [x]  Ensure the component has a root story file in the component directory
- [x]  Ensure that the root story file exports a Default story
- [x]  (Optional) Create a Playground story
- [x]  Move all other stories for the component into a .features.stories.tsx file
- [x]  Opt the component into storybook tests
- [ ]  (Optional) Create visual regression tests for the component

2023-10-30 23:07 UTC, broccolinisoup requested changes
Thanks so much for this PR 🙌🏻 It is looking good - just missing an update on the `doc/content/Tooltip.mdx` 

We should update the source code and the component data on `doc/content/Tooltip.mdx` 

Source Code 

```diff
-https://github.com/primer/react/blob/main/src/Tooltip.tsx
+https://github.com/primer/react/blob/main/src/Tooltip/Tooltip.tsx
```

Component data import 

```diff
-import data from '../../src/Tooltip.docs.json'
+import data from '../../src/Tooltip/Tooltip.docs.json'
```

After that it should be good 🤞🏻 Let me know if you have any concerns!

2023-10-31 13:47 UTC, green6erry commented
> Thanks so much for this PR 🙌🏻 It is looking good - just missing an update on the `doc/content/Tooltip.mdx`
> 
> We should update the source code and the component data on `doc/content/Tooltip.mdx`
> 
> Source Code
> 
> ```diff
> -https://github.com/primer/react/blob/main/src/Tooltip.tsx
> +https://github.com/primer/react/blob/main/src/Tooltip/Tooltip.tsx
> ```
> 
> Component data import
> 
> ```diff
> -import data from '../../src/Tooltip.docs.json'
> +import data from '../../src/Tooltip/Tooltip.docs.json'
> ```
> 
> After that it should be good 🤞🏻 Let me know if you have any concerns!

Completed!

2023-10-31 17:22 UTC, green6erry reviewed
Should be all fixed!

2023-10-31 17:33 UTC, joshblack approved these changes

2023-10-31 21:34 UTC, broccolinisoup approved these changes

2023-10-31 21:46 UTC, merged