Fix MarkdownEditor fullHeight support
primer/react pull request #3893
Opened 2023-11-01 08:59 UTC by stkao05

Closes #

### Changelog

#### Changed

Currently the MarkdownEditor's `fullHeight` props didn't take effect as the height change wasn't applied to the outer most container element (`<fieldset>`)

### Rollout strategy

- [x] Patch release
- [ ] Minor release
- [ ] Major release; if selected, include a written rollout or migration plan

### Testing & Reviewing

### Merge checklist

- [ ] Added/updated tests
- [ ] Added/updated documentation
- [x] Added/updated previews (Storybook)
- [ ] Changes are [SSR compatible](https://github.com/primer/react/blob/main/contributor-docs/CONTRIBUTING.md#ssr-compatibility)
- [ ] Tested in Chrome
- [ ] Tested in Firefox
- [ ] Tested in Safari
- [ ] Tested in Edge

2023-11-02 11:46 UTC, cs25-esc commented
Hi @stkao05 can you help to write a changeset for my PR https://github.com/primer/react/pull/3895 please?

2023-11-02 12:31 UTC, siddharthkp commented on .changeset/fluffy-months-invite.md
> +---
There are 2 changesets here, I imagine you only want the `patch` one?

2023-11-02 12:37 UTC, siddharthkp requested changes
Left a couple of comments

2023-11-07 13:12 UTC, stkao05 commented on src/drafts/MarkdownEditor/MarkdownEditor.stories.tsx
> +      <div style={{height: '400px'}}>
I set the height of this element so we can test if the child `MarkdownEditor` component does extends to full height to its parent element height. 

But I agree it is a bit confusing from the code. I can add comment or remove the change if you think it isn't needed.

2023-11-07 13:19 UTC, stkao05 commented on src/drafts/MarkdownEditor/MarkdownEditor.stories.tsx
> +      <div style={{height: '400px'}}>
Remove the change for now.

2023-11-07 13:21 UTC, stkao05 commented
Thanks for reviewing. Just update the PR accordingly.

2023-11-07 14:28 UTC, siddharthkp commented
@stkao05, There are some recent changes in `main` as well, can you merge latest `main` into your branch?

2023-11-07 17:54 UTC, stkao05 commented
> There are some recent changes to MarkdownEditor in `main` as well, can you merge latest `main` into your branch?

no problem. just did 👌

2023-11-08 15:39 UTC, siddharthkp approved these changes
This looks good! Will merge after CI passes :)

2023-11-08 15:48 UTC, merged