Update Link `inline` prop description and deprecate `underline`
primer/react pull request #4135
Opened 2024-01-09 19:02 UTC by dipree

https://github.com/github/primer/issues/2099

Updates the Link `inline` property description and set the `underline` property to "deprecated".

2024-01-11 16:10 UTC, joshblack requested changes
Thanks for doing this! Just left a comment on where `@deprecated` could live, hope it makes sense and let me know if you have any questions!

2024-01-11 16:10 UTC, joshblack commented on src/Link/Link.tsx
> +  /** @deprecated */
```suggestion
```

I think the notice could live on `StyledLinkProps` above like:

```tsx
type StyledLinkProps = {
  hoverColor?: string
  muted?: boolean
  /** @deprecated use `inline` to specify the type of link instead */
  underline?: boolean
  // Link inside a text block
  inline?: boolean
} & SxProp
```

Hope that makes sense! This should mean that folks get this kind of error in their IDE of choice:

![An editor showing the deprecation message for the underline prop in a code snippet](https://github.com/primer/react/assets/3901764/64ee101c-4f79-4634-9605-8e58140513dc)

2024-01-11 16:18 UTC, dipree commented
@joshblack I see how that works now, thanks and updated.

2024-01-12 17:45 UTC, joshblack approved these changes

2024-01-12 18:45 UTC, merged