Resolves #4672
primer/react pull request #4745
Opened 2024-07-17 12:32 UTC by cihad

Resolves #4672

### Changelog

#### New

#### Changed

#### Removed

### Rollout strategy

- [ ] Patch release
- [ ] Minor release
- [ ] Major release; if selected, include a written rollout or migration plan
- [ ] None; if selected, include a brief description as to why

### Testing & Reviewing

### Merge checklist

- [ ] Added/updated tests
- [ ] Added/updated documentation
- [ ] Added/updated previews (Storybook)
- [ ] Changes are [SSR compatible](https://github.com/primer/react/blob/main/contributor-docs/CONTRIBUTING.md#ssr-compatibility)
- [ ] Tested in Chrome
- [ ] Tested in Firefox
- [ ] Tested in Safari
- [ ] Tested in Edge
- [ ] (GitHub staff only) Integration tests pass at github/github ([Learn more about how to run integration tests](https://github.com/github/primer-engineering/blob/main/how-we-work/testing-primer-react-pr-at-dotcom.md))

2024-07-19 02:19 UTC, broccolinisoup requested changes
Hey @cihad 👋🏻 Thanks so much for pushing this PR! The changes looks good to me. Could you please [add a changeset](https://github.com/changesets/changesets/blob/main/docs/adding-a-changeset.md) and fill out the PR description? 🙏🏻

2024-09-13 21:30 UTC, TylerJDev commented
Hey @cihad! Just wanted to follow-up and see if you were still working on this PR? I see it's nearly finished, it looks like it just needs a changeset and an update to your PR description. Thank you too for your contribution!

2024-11-12 01:22 UTC, broccolinisoup commented on .changeset/erken-gelen-oturur.md
> +Updates loading counter for UnderlineNav.Item component
```suggestion
UnderlineNav: Display loading counters only for items with the "counter" prop.
```

2024-11-12 01:23 UTC, broccolinisoup approved these changes

2024-11-12 01:39 UTC, merged