Implement code connect for segmentedControl
primer/react pull request #4849
Opened 2024-08-14 09:29 UTC by lukasoppermann

![CleanShot 2024-08-14 at 11 28 22@2x](https://github.com/user-attachments/assets/c20feccd-4a3b-4e52-bf0c-f8912a619c6b)

2024-08-15 15:04 UTC, joshblack commented
> Also @joshblack I think the SegmentedContorl has the same issue with leadingIcon where it does only accept a function but not an element. Can we fix that?

@lukasoppermann definitely! I think it should be just as doable as the last component with this issue 👍 This could be a good issue for FR to take on (adding support for element to loadingIcon) since it should be quick

2024-09-26 11:26 UTC, lukasoppermann commented
After discussing with @siddharthkp we should keep the current behavior in the segmentedControl, as it otherwise leaves us open to unwanted customization in the icons.

I talked to Figma and they are working on a fix. We are hoping to get this in the next week, but until then this is blocked.

2024-12-17 20:16 UTC, langermank requested changes

2024-12-17 20:17 UTC, langermank commented on packages/react/package.json
> +    "@primer/octicons-react": "^19.12.0",
Could just try and get this passing and ready for review https://github.com/primer/react/pull/5422

2024-12-18 12:37 UTC, lukasoppermann commented on packages/react/package.json
> +    "@primer/octicons-react": "^19.12.0",
I did revert octicons but the snapshots don't go away.

@TylerJDev I do need this update, but we can do this in a separate PR.

2024-12-19 01:00 UTC, langermank approved these changes
Good to go 🚀

2024-12-19 01:08 UTC, merged