Bug fix styled spinner
primer/react pull request #5236
Opened 2024-11-05 20:15 UTC by jonrohan

Closes #

### Changelog

#### New

#### Changed

#### Removed

### Rollout strategy

- [ ] Patch release
- [ ] Minor release
- [ ] Major release; if selected, include a written rollout or migration plan
- [ ] None; if selected, include a brief description as to why

### Testing & Reviewing

### Merge checklist

- [ ] Added/updated tests
- [ ] Added/updated documentation
- [ ] Added/updated previews (Storybook)
- [ ] Changes are [SSR compatible](https://github.com/primer/react/blob/main/contributor-docs/CONTRIBUTING.md#ssr-compatibility)
- [ ] Tested in Chrome
- [ ] Tested in Firefox
- [ ] Tested in Safari
- [ ] Tested in Edge
- [ ] (GitHub staff only) Integration tests pass at github/github ([Learn more about how to run integration tests](https://github.com/github/primer-engineering/blob/main/how-we-work/testing-primer-react-pr-at-dotcom.md))

2024-11-05 21:27 UTC, randall-krauskopf approved these changes

2024-11-05 21:29 UTC, joshblack requested changes

2024-11-05 21:29 UTC, joshblack commented on .changeset/forty-rats-jog.md
> +Spinner component size get's large when passing sx and size props
I think typo here for gets:

```suggestion
Spinner component size gets large when passing sx and size props
```

An alternative for the changelog too, not sure if it fully captures what is being changed though:

```suggestion
Update Spinner component to correctly use the `size` prop when both `sx` and `size` are provided
```

2024-11-05 21:29 UTC, joshblack commented on packages/react/src/Spinner/Spinner.dev.stories.tsx
> +export const Default = () => <Spinner sx={{border: '1px solid red'}} size={'small'} />
For text-only values we can use this syntax instead:

```suggestion
export const Default = () => <Spinner sx={{border: '1px solid red'}} size="small" />
```

2024-11-05 21:31 UTC, jonrohan commented on packages/react/src/Spinner/Spinner.tsx
> +    return <Spinner className={clsx(className, classes.SpinnerAnimation)} {...props} />
Not related to the bug, but was pointed out that className was overwriting the CSS modules classname when being passed in, so I added this

2024-11-05 22:03 UTC, hussam-i-am approved these changes

2024-11-06 19:36 UTC, joshblack approved these changes

2024-11-06 19:47 UTC, merged