Dialog: Show `Tooltip` on "close" button
primer/react pull request #5436
Opened 2024-12-13 16:24 UTC by TylerJDev

Part of https://github.com/github/primer/issues/3726

Removes `unsafeDisableTooltip` from `IconButton` in `Dialog`, and removes eslint disable along with it.

### Changelog

#### Removed

- Removed unsafeDisableTooltip

### Rollout strategy

- [x] Patch release
- [ ] Minor release
- [ ] Major release; if selected, include a written rollout or migration plan
- [ ] None; if selected, include a brief description as to why

### Testing & Reviewing

### Merge checklist

- [ ] Added/updated tests
- [ ] Added/updated documentation
- [ ] Added/updated previews (Storybook)
- [ ] Changes are [SSR compatible](https://github.com/primer/react/blob/main/contributor-docs/CONTRIBUTING.md#ssr-compatibility)
- [x] Tested in Chrome
- [ ] Tested in Firefox
- [ ] Tested in Safari
- [ ] Tested in Edge
- [ ] (GitHub staff only) Integration tests pass at github/github ([Learn more about how to run integration tests](https://github.com/github/primer-engineering/blob/main/how-we-work/testing-primer-react-pr-at-dotcom.md))

2024-12-13 16:50 UTC, TylerJDev commented
Some of the snapshots look a bit odd due to the tooltip placement, but I believe this is just something with how the snapshots were taken (maybe timing?) and not an actual issue with the tooltip, as it cannot be produced locally.

2024-12-16 22:09 UTC, langermank approved these changes
@TylerJDev those snapshots are kind of scary! Could we maybe adjust the test to add a short delay? Do you think that's the issue? 🤔

2024-12-17 04:54 UTC, broccolinisoup commented
@TylerJDev @langermank sorry to barge in 🙃  I saw the Slack notification and wanted to mention that we have one open issue regarding Tooltip misplacement on Dialogs that we probably need to fix it first 😬 https://github.com/primer/react/issues/4734

2025-01-07 21:22 UTC, Amk-001 requested changes
Reconnect

2025-03-19 16:51 UTC, TylerJDev commented on packages/react/src/Dialog/Dialog.dev.stories.tsx
> +          sx={{borderColor: 'accent.emphasis', borderWidth: '1px', borderStyle: 'solid', animation: 'none !important'}}
There was a very small difference between the `dev` component snapshots (0.02 pixel difference). It seems like this was caused by the animation, but only [affected the colorblind theme](https://github.com/primer/react/pull/5791/files#diff-b524b7368a3a947aab78b8c4429e5ee36858a6673007b4e1ed8a7dad12559de7). 

It would sometimes pass/fail, so I marked it off as being flaky via the custom CSS. It never affected the non-dev stories.

2025-03-19 17:03 UTC, langermank approved these changes
Excellent work solving this very weird, annoying problem!

2025-03-20 21:12 UTC, merged